### ISSUE TITLE
Have you published anything in English?

### ISSUE THREAD

**Issue by JJ** [pitaatip/DJevolution#11]
@mariosky and myself would be interested in reading about it.

**Comment by pitaatip** [comment]
Hi,
I've prepared small doc + user guide lately, but unfortunatelly it is in Polish.
I am about to translate it to English and I hope it won't take longer than 2 weeks.
Soon, we'll also upload shortest, easiest and more actual guide how to set up and run DJevolution.

So stay tuned!

**Comment by wysekm** [comment]
Also we are planning to publish a paper about the application and the project behind it, however it's still in the preliminary phase. We will keep you informed if there's any progress.

**Comment by mariosky** [comment]
We have been working  in two parallel EA models. SofEA an EvoSpace.
EvoSpace has been implemented in Python and Redis. With cherrypy and also
Django. Maybe it could be of interest for your work.

Please keep us informed of your progress.

Mario
