### ISSUE TITLE
Notatka do obliczenia

### ISSUE THREAD

**Issue by pitaatip** [pitaatip/DJevolution#12]
Myślę, że notatkę powinno się dać edytować zarówno przy uruchamianiu obliczenia jak i przy wyświetlaniu wyników na pierwszej stronie obliczenia.

Aby zapisać nowe pole, wzbogać model obliczenia (zob. models.py)

Przy uruchamianiu: trzeba dodać nowe pole do formularza (zob. ComputationForm w models.py, tworzenie go w views.py i użycie na stronie general.html).

Przy wyświetlaniu obliczenia: Nie ma formularza, dlatego trzeba stworzyć nowy i umieścić go w rozsądnym miejscu, zobacz jak to jest robione z innymi formami.

Można się też zastanowić czy nie przedstawiać fragmentu notatki (np 30 znaków pierwszych, w tabelce obliczeń na głównej stronie DJevol)

**Comment by wysekm** [comment]
Zrobione zgodnie ze specyfikacją.
