### ISSUE TITLE
Umożliwienie zapisywania spacing co x iteracji

### ISSUE THREAD

**Issue by pitaatip** [pitaatip/DJevolution#14]
Na widoku: zmiana formularza używanego na monitoring.html (z checkboxa na input).

W modelu danych: zmiana flagi bool na wartość liczbową

W engine: obliczanie spacing co x obrotów pętli - tak jest teraz liczony partial_results i możesz to zrobić analogicznie).

**Comment by wysekm** [comment]
Done. 

Niestety nie rozumiem dlaczego pomimo ustawienia w modelu integer field parametru null=True pozostawienie pustego pola generuje pusty http response. Ale chce, żeby to już było, więc zrobiłem commita do branacha o profesjonalnie brzmiącej nazwie branch_for_issues_12-14.

Teraz tylko problemem jest to, że w High Chartsach wyświetlaja się spacing dla kolejnych generacji, co dla nowego typu obliczania nie jest prawda. (przy obliczaniu co 5 dla 200 iter wyświetla się tak jakby 40 generacji)

**Comment by wysekm** [comment]
Zrobione.
