### ISSUE TITLE
Decission on queueing system

### ISSUE THREAD

**Issue by wysekm** [pitaatip/DJevolution#5]
Należy się zastanowić nad systemem kolejkowania zadań. W tym momencie w przypadku obecności 4 węzłów obliczeniowych i uruchomienia więcej niż 4 procesów (w ramach tego samego zadania/różnych zadań) nie będą one w żaden sposób kolejkowane co doprowadzi do spadku wydajności spowodowanego uruchomieniem więcej niż jednego procesu na jednym rdzeniu procesora i może doprowadzić do wyczerpania zasobów danej stacji roboczej.

Rozwiązania jakie widzę:
- zintegrowanie systemu kolejkowania i schedulingu zadań we frameworku
- wykorzystanie gotowych rozwiązań np Torque

**Comment by pitaatip** [comment]
Wydaje mi się, że trzeba po pierwsze zobaczyć jakich możliwości dostarcza DTM. Mam wrażenie że on jest odpowiedzialny za kolejkowanie oraz zarządzanie zadaniami. Mając strukturę klastra 4 węzłów, uruchamiając program w sposób rozproszony przy użyciu MPI i zlecając wykonania odpowiednich obliczeń poprzez funkcje DTM (dtm.map() ) zostawiamy jemu zarządzanie zasobami i zadaniami.

**Comment by wysekm** [comment]
Nie do końca o to chodzi. W momencie posiadania 4 węzłów obliczeniowych jeżeli odpalimy na wszystkich z nich jedno zadanie (przez zadanie rozumiem instancję aplikacji) to zostaną stworzone 4 procesy na 4 procesorach.
Jeżeli przed końcem zadania odpalimy kolejną instancję aplikacji znowu na 4 rdzeniach, to kolejne 4 procesy zostaną odpalone na tych samych węzłach obliczeniowych i będą konkurować ze sobą o zasoby systemu.

Idealne rozwiązanie zakładałoby kolejkowanie tych zadań w jakiś sposób i wstrzymanie ich wykonania do momentu pojawienia się potrzebnych zasobów.

**Comment by pitaatip** [comment]
Ok, w takim razie możemy sobie na razie ustalić, że odpalamy po jednym obliczeniu. To o czym mówisz będzie musiało zostać rozwiązane przez naszego demona obliczeń, który monitorując bazę danych będzie wykrywał obliczenia zlecone mu przez prezentację i je realizował. W tym momencie od nas zależy czy demon ten będzie czekał na wykonanie się każdego zadania (odpalenie po jednej instacji obliczeń przez MPI) czy też będzie je odpalał jak tylko je zauważy a osobny system kolejkujący będzie dbał o odpowiednią kolejność zadań.
