### ISSUE TITLE
Simple genetic algorithm

### ISSUE THREAD

**Issue by pitaatip** [pitaatip/DJevolution#6]
Sprawdzić czy implementacja z deap operuje na kodowaniu binarnym.

**Comment by wysekm** [comment]
Deap nie używa kodowania binarnego (zamiast niego używa kontenerów i to na ich elementach wykonuje operacje genetyczne). Jednak miejscami twórcy powołują się na artykuły/implementacje używane przez innych w zagadnieniach genetycznych. Więc może nie trzeba by było od razu kwestionować tych metod.

Jeżeli jednak trzeba będzie faktycznie działać na kodowaniu binarnym, musielibyśmy napisać własne funkcje mutacji, crossowania itd jednak nie wydaje mi się, żeby było to zbyt trudne, jeżeli będziemy wiedzieli dokładnie jak mają wyglądać te algorytmy.
