### ISSUE TITLE
Official DEAP Version

### ISSUE THREAD

**Issue by wysekm** [pitaatip/DJevolution#8]
Trzeba się zastanowić nad używaną przez nas wersją deapa.
Ja proponuje 0.8, próbowałem zainstalować teraz 0.7 ale miałem problem.
Zresztą wszystkie przykłady, które oni publikują są napisane w 0.8

**Comment by pitaatip** [comment]
Jestem za, postaram sie dziś przesiąść
21-04-2012 11:28 użytkownik "wysekm" <
reply@reply.github.com>
napisał:
