### ISSUE TITLE
Problem with urls.py

### ISSUE THREAD

**Issue by wysekm** [pitaatip/DJevolution#9]
Zapomniałeś chyba dodać niektórych katalogów do gita, bo przy odpaleniu strony w przeglądarce wyrzuca mi błąd w pliku urls.py o niedostępnych ścieżkach (np VisualApp/comp, VisualApp/del_comp).

**Comment by pitaatip** [comment]
jakich katalogów brakuje? nie ma ustawionych gdzieś na sztywno
ścieżek? rzuce okiem jak będę miał komputer.

20.07.2012, wysekm
reply@reply.github.com
napisał(a):

**Comment by wysekm** [comment]
Dostaję następujący błąd przy próbie połączenia ze stroną pod 127.0.0.1:8000:
Using the URLconf defined in VisualController.urls, Django tried these URL patterns, in this order:
"""
    ^VisualControllerApp/comp/(?P<pk>[a-z\d]+)/$ [name='comp_detail']
    ^VisualControllerApp/$ [name='computation_list']
    ^VisualControllerApp/delete_comp/(?P<pk>[a-z\d]+)/$ [name='comp_delete']
    ^VisualControllerApp/orderComputation/$
    ^admin/doc/
    ^admin/

The current URL, , didn't match any of these.
"""
I faktycznie, jedyne pliki jakie mam w VisualControllerApp to:
__init__.py
test.py
models.py
views.py
Katalog główny Django, który mam ustawiony to: VisualController
